### ISSUE TITLE
gt_flow

### ISSUE THREAD

**Issue by liu-wei-song** [hyzhou404/HUGSIM#3]
Hello! Thank you for your excellent work and open source!
"gt_flow" doesn't seem to have been used

**Comment by liu-wei-song** [comment]
It seems that I can combine HUGS and HUGSIM_splat to understand the code?

**Comment by hyzhou404** [comment]
3DGS can render acceptable flow without any supervision. While HUGS uses a flow loss to supervise flow rendering, we've removed this loss in HUGSIM.  Because we found that the flow loss doesn't show necessity for conducting a closed-loop simulator. Depth is similar; we simply render flow and depth as additional modalities without any supervision during training stage.

**Comment by liu-wei-song** [comment]
thanks a lot🌹
