### ISSUE TITLE
Question about python environment

### ISSUE THREAD

**Issue by suminmin** [hyzhou404/HUGSIM#6]
Thank you for sharing your excellent work!

I have a question regarding running closed_loop.py and e2e.py. Initially, I attempted to install both HUGSIM and UniAD_SIM under the same environment, but I couldn't get it to work. Upon further investigation, I came across the following line in the code:

[UniAD_SIM](https://github.com/hyzhou404/UniAD_SIM/tree/main)/[tools](https://github.com/hyzhou404/UniAD_SIM/tree/main/tools)/e2e.sh

`conda activate uniad`

Does this imply that two separate Python environments need to be prepared with Conda?

One for HUGSIM, using Python 3.11 with `torch==2.2.0`, and another for UniAD/VAD, using Python 3.8 with `torch==1.9.1`, `mmcv-full==1.4.0`, and `mmdet3d==0.17.1`.

**Comment by hyzhou404** [comment]
Hello, as a simulator, we don't require client algorithms to use the same environment as ours. Therefore, we maintain separate Python environments for the simulator and the client. For UniAD, please refer to the official installation instructions, the specific package versions may differ from your CUDA environments. Since the official UniAD implementation does not provide direct inference code, we recommend using our modified version of UniAD available at https://github.com/hyzhou404/UniAD_SIM.

**Comment by suminmin** [comment]
Thanks for the clarification!

**Comment by rdesc** [comment]
Can this info maybe be added to the readme here https://github.com/hyzhou404/HUGSIM?tab=readme-ov-file#simulation ?
